// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countActiveJobsByChargeAddressStmt, err = db.PrepareContext(ctx, countActiveJobsByChargeAddress); err != nil {
		return nil, fmt.Errorf("error preparing query CountActiveJobsByChargeAddress: %w", err)
	}
	if q.countNonceStmt, err = db.PrepareContext(ctx, countNonce); err != nil {
		return nil, fmt.Errorf("error preparing query CountNonce: %w", err)
	}
	if q.createBotStmt, err = db.PrepareContext(ctx, createBot); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBot: %w", err)
	}
	if q.createEventStmt, err = db.PrepareContext(ctx, createEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEvent: %w", err)
	}
	if q.createJobStmt, err = db.PrepareContext(ctx, createJob); err != nil {
		return nil, fmt.Errorf("error preparing query CreateJob: %w", err)
	}
	if q.createOfferStmt, err = db.PrepareContext(ctx, createOffer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOffer: %w", err)
	}
	if q.createPayloadStmt, err = db.PrepareContext(ctx, createPayload); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePayload: %w", err)
	}
	if q.deleteEventsBeforeStmt, err = db.PrepareContext(ctx, deleteEventsBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEventsBefore: %w", err)
	}
	if q.deleteIdempotencyBeforeStmt, err = db.PrepareContext(ctx, deleteIdempotencyBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIdempotencyBefore: %w", err)
	}
	if q.deleteNoncesBeforeStmt, err = db.PrepareContext(ctx, deleteNoncesBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNoncesBefore: %w", err)
	}
	if q.deletePayloadsBeforeStmt, err = db.PrepareContext(ctx, deletePayloadsBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePayloadsBefore: %w", err)
	}
	if q.getBotStmt, err = db.PrepareContext(ctx, getBot); err != nil {
		return nil, fmt.Errorf("error preparing query GetBot: %w", err)
	}
	if q.getIdempotencyStmt, err = db.PrepareContext(ctx, getIdempotency); err != nil {
		return nil, fmt.Errorf("error preparing query GetIdempotency: %w", err)
	}
	if q.getJobStmt, err = db.PrepareContext(ctx, getJob); err != nil {
		return nil, fmt.Errorf("error preparing query GetJob: %w", err)
	}
	if q.getMinEventIDStmt, err = db.PrepareContext(ctx, getMinEventID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMinEventID: %w", err)
	}
	if q.getOfferStmt, err = db.PrepareContext(ctx, getOffer); err != nil {
		return nil, fmt.Errorf("error preparing query GetOffer: %w", err)
	}
	if q.getPayloadStmt, err = db.PrepareContext(ctx, getPayload); err != nil {
		return nil, fmt.Errorf("error preparing query GetPayload: %w", err)
	}
	if q.getPollAckStmt, err = db.PrepareContext(ctx, getPollAck); err != nil {
		return nil, fmt.Errorf("error preparing query GetPollAck: %w", err)
	}
	if q.insertIdempotencyStmt, err = db.PrepareContext(ctx, insertIdempotency); err != nil {
		return nil, fmt.Errorf("error preparing query InsertIdempotency: %w", err)
	}
	if q.insertNonceStmt, err = db.PrepareContext(ctx, insertNonce); err != nil {
		return nil, fmt.Errorf("error preparing query InsertNonce: %w", err)
	}
	if q.insertOfferTagStmt, err = db.PrepareContext(ctx, insertOfferTag); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOfferTag: %w", err)
	}
	if q.listEventsAfterIDStmt, err = db.PrepareContext(ctx, listEventsAfterID); err != nil {
		return nil, fmt.Errorf("error preparing query ListEventsAfterID: %w", err)
	}
	if q.listJobsByBuyerNewestStmt, err = db.PrepareContext(ctx, listJobsByBuyerNewest); err != nil {
		return nil, fmt.Errorf("error preparing query ListJobsByBuyerNewest: %w", err)
	}
	if q.listJobsByBuyerNewestAfterStmt, err = db.PrepareContext(ctx, listJobsByBuyerNewestAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListJobsByBuyerNewestAfter: %w", err)
	}
	if q.listJobsByBuyerSinceStmt, err = db.PrepareContext(ctx, listJobsByBuyerSince); err != nil {
		return nil, fmt.Errorf("error preparing query ListJobsByBuyerSince: %w", err)
	}
	if q.listJobsByBuyerSinceAfterStmt, err = db.PrepareContext(ctx, listJobsByBuyerSinceAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListJobsByBuyerSinceAfter: %w", err)
	}
	if q.listJobsBySellerNewestStmt, err = db.PrepareContext(ctx, listJobsBySellerNewest); err != nil {
		return nil, fmt.Errorf("error preparing query ListJobsBySellerNewest: %w", err)
	}
	if q.listJobsBySellerNewestAfterStmt, err = db.PrepareContext(ctx, listJobsBySellerNewestAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListJobsBySellerNewestAfter: %w", err)
	}
	if q.listJobsBySellerSinceStmt, err = db.PrepareContext(ctx, listJobsBySellerSince); err != nil {
		return nil, fmt.Errorf("error preparing query ListJobsBySellerSince: %w", err)
	}
	if q.listJobsBySellerSinceAfterStmt, err = db.PrepareContext(ctx, listJobsBySellerSinceAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListJobsBySellerSinceAfter: %w", err)
	}
	if q.listOfferIDsByTagStmt, err = db.PrepareContext(ctx, listOfferIDsByTag); err != nil {
		return nil, fmt.Errorf("error preparing query ListOfferIDsByTag: %w", err)
	}
	if q.listOfferTagsStmt, err = db.PrepareContext(ctx, listOfferTags); err != nil {
		return nil, fmt.Errorf("error preparing query ListOfferTags: %w", err)
	}
	if q.listOffersNewestStmt, err = db.PrepareContext(ctx, listOffersNewest); err != nil {
		return nil, fmt.Errorf("error preparing query ListOffersNewest: %w", err)
	}
	if q.listOffersNewestAfterStmt, err = db.PrepareContext(ctx, listOffersNewestAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListOffersNewestAfter: %w", err)
	}
	if q.listPayloadMetadataAllStmt, err = db.PrepareContext(ctx, listPayloadMetadataAll); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayloadMetadataAll: %w", err)
	}
	if q.listPayloadMetadataAllAfterStmt, err = db.PrepareContext(ctx, listPayloadMetadataAllAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayloadMetadataAllAfter: %w", err)
	}
	if q.listPayloadMetadataFetchedStmt, err = db.PrepareContext(ctx, listPayloadMetadataFetched); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayloadMetadataFetched: %w", err)
	}
	if q.listPayloadMetadataFetchedAfterStmt, err = db.PrepareContext(ctx, listPayloadMetadataFetchedAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayloadMetadataFetchedAfter: %w", err)
	}
	if q.listPayloadMetadataUnfetchedStmt, err = db.PrepareContext(ctx, listPayloadMetadataUnfetched); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayloadMetadataUnfetched: %w", err)
	}
	if q.listPayloadMetadataUnfetchedAfterStmt, err = db.PrepareContext(ctx, listPayloadMetadataUnfetchedAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListPayloadMetadataUnfetchedAfter: %w", err)
	}
	if q.markPayloadFetchedStmt, err = db.PrepareContext(ctx, markPayloadFetched); err != nil {
		return nil, fmt.Errorf("error preparing query MarkPayloadFetched: %w", err)
	}
	if q.updateBotLastSeenStmt, err = db.PrepareContext(ctx, updateBotLastSeen); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBotLastSeen: %w", err)
	}
	if q.updateJobCancelStmt, err = db.PrepareContext(ctx, updateJobCancel); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateJobCancel: %w", err)
	}
	if q.updateJobChargeStmt, err = db.PrepareContext(ctx, updateJobCharge); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateJobCharge: %w", err)
	}
	if q.updateJobDeliverStmt, err = db.PrepareContext(ctx, updateJobDeliver); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateJobDeliver: %w", err)
	}
	if q.updateJobExpireStmt, err = db.PrepareContext(ctx, updateJobExpire); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateJobExpire: %w", err)
	}
	if q.updateJobMarkPaidStmt, err = db.PrepareContext(ctx, updateJobMarkPaid); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateJobMarkPaid: %w", err)
	}
	if q.updateOfferCancelStmt, err = db.PrepareContext(ctx, updateOfferCancel); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOfferCancel: %w", err)
	}
	if q.updateOfferExpireStmt, err = db.PrepareContext(ctx, updateOfferExpire); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOfferExpire: %w", err)
	}
	if q.upsertPollAckStmt, err = db.PrepareContext(ctx, upsertPollAck); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertPollAck: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countActiveJobsByChargeAddressStmt != nil {
		if cerr := q.countActiveJobsByChargeAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countActiveJobsByChargeAddressStmt: %w", cerr)
		}
	}
	if q.countNonceStmt != nil {
		if cerr := q.countNonceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countNonceStmt: %w", cerr)
		}
	}
	if q.createBotStmt != nil {
		if cerr := q.createBotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBotStmt: %w", cerr)
		}
	}
	if q.createEventStmt != nil {
		if cerr := q.createEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEventStmt: %w", cerr)
		}
	}
	if q.createJobStmt != nil {
		if cerr := q.createJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createJobStmt: %w", cerr)
		}
	}
	if q.createOfferStmt != nil {
		if cerr := q.createOfferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOfferStmt: %w", cerr)
		}
	}
	if q.createPayloadStmt != nil {
		if cerr := q.createPayloadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPayloadStmt: %w", cerr)
		}
	}
	if q.deleteEventsBeforeStmt != nil {
		if cerr := q.deleteEventsBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEventsBeforeStmt: %w", cerr)
		}
	}
	if q.deleteIdempotencyBeforeStmt != nil {
		if cerr := q.deleteIdempotencyBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteIdempotencyBeforeStmt: %w", cerr)
		}
	}
	if q.deleteNoncesBeforeStmt != nil {
		if cerr := q.deleteNoncesBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNoncesBeforeStmt: %w", cerr)
		}
	}
	if q.deletePayloadsBeforeStmt != nil {
		if cerr := q.deletePayloadsBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePayloadsBeforeStmt: %w", cerr)
		}
	}
	if q.getBotStmt != nil {
		if cerr := q.getBotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBotStmt: %w", cerr)
		}
	}
	if q.getIdempotencyStmt != nil {
		if cerr := q.getIdempotencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIdempotencyStmt: %w", cerr)
		}
	}
	if q.getJobStmt != nil {
		if cerr := q.getJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getJobStmt: %w", cerr)
		}
	}
	if q.getMinEventIDStmt != nil {
		if cerr := q.getMinEventIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMinEventIDStmt: %w", cerr)
		}
	}
	if q.getOfferStmt != nil {
		if cerr := q.getOfferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOfferStmt: %w", cerr)
		}
	}
	if q.getPayloadStmt != nil {
		if cerr := q.getPayloadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPayloadStmt: %w", cerr)
		}
	}
	if q.getPollAckStmt != nil {
		if cerr := q.getPollAckStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPollAckStmt: %w", cerr)
		}
	}
	if q.insertIdempotencyStmt != nil {
		if cerr := q.insertIdempotencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertIdempotencyStmt: %w", cerr)
		}
	}
	if q.insertNonceStmt != nil {
		if cerr := q.insertNonceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertNonceStmt: %w", cerr)
		}
	}
	if q.insertOfferTagStmt != nil {
		if cerr := q.insertOfferTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOfferTagStmt: %w", cerr)
		}
	}
	if q.listEventsAfterIDStmt != nil {
		if cerr := q.listEventsAfterIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEventsAfterIDStmt: %w", cerr)
		}
	}
	if q.listJobsByBuyerNewestStmt != nil {
		if cerr := q.listJobsByBuyerNewestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listJobsByBuyerNewestStmt: %w", cerr)
		}
	}
	if q.listJobsByBuyerNewestAfterStmt != nil {
		if cerr := q.listJobsByBuyerNewestAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listJobsByBuyerNewestAfterStmt: %w", cerr)
		}
	}
	if q.listJobsByBuyerSinceStmt != nil {
		if cerr := q.listJobsByBuyerSinceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listJobsByBuyerSinceStmt: %w", cerr)
		}
	}
	if q.listJobsByBuyerSinceAfterStmt != nil {
		if cerr := q.listJobsByBuyerSinceAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listJobsByBuyerSinceAfterStmt: %w", cerr)
		}
	}
	if q.listJobsBySellerNewestStmt != nil {
		if cerr := q.listJobsBySellerNewestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listJobsBySellerNewestStmt: %w", cerr)
		}
	}
	if q.listJobsBySellerNewestAfterStmt != nil {
		if cerr := q.listJobsBySellerNewestAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listJobsBySellerNewestAfterStmt: %w", cerr)
		}
	}
	if q.listJobsBySellerSinceStmt != nil {
		if cerr := q.listJobsBySellerSinceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listJobsBySellerSinceStmt: %w", cerr)
		}
	}
	if q.listJobsBySellerSinceAfterStmt != nil {
		if cerr := q.listJobsBySellerSinceAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listJobsBySellerSinceAfterStmt: %w", cerr)
		}
	}
	if q.listOfferIDsByTagStmt != nil {
		if cerr := q.listOfferIDsByTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOfferIDsByTagStmt: %w", cerr)
		}
	}
	if q.listOfferTagsStmt != nil {
		if cerr := q.listOfferTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOfferTagsStmt: %w", cerr)
		}
	}
	if q.listOffersNewestStmt != nil {
		if cerr := q.listOffersNewestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOffersNewestStmt: %w", cerr)
		}
	}
	if q.listOffersNewestAfterStmt != nil {
		if cerr := q.listOffersNewestAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOffersNewestAfterStmt: %w", cerr)
		}
	}
	if q.listPayloadMetadataAllStmt != nil {
		if cerr := q.listPayloadMetadataAllStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPayloadMetadataAllStmt: %w", cerr)
		}
	}
	if q.listPayloadMetadataAllAfterStmt != nil {
		if cerr := q.listPayloadMetadataAllAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPayloadMetadataAllAfterStmt: %w", cerr)
		}
	}
	if q.listPayloadMetadataFetchedStmt != nil {
		if cerr := q.listPayloadMetadataFetchedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPayloadMetadataFetchedStmt: %w", cerr)
		}
	}
	if q.listPayloadMetadataFetchedAfterStmt != nil {
		if cerr := q.listPayloadMetadataFetchedAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPayloadMetadataFetchedAfterStmt: %w", cerr)
		}
	}
	if q.listPayloadMetadataUnfetchedStmt != nil {
		if cerr := q.listPayloadMetadataUnfetchedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPayloadMetadataUnfetchedStmt: %w", cerr)
		}
	}
	if q.listPayloadMetadataUnfetchedAfterStmt != nil {
		if cerr := q.listPayloadMetadataUnfetchedAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPayloadMetadataUnfetchedAfterStmt: %w", cerr)
		}
	}
	if q.markPayloadFetchedStmt != nil {
		if cerr := q.markPayloadFetchedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markPayloadFetchedStmt: %w", cerr)
		}
	}
	if q.updateBotLastSeenStmt != nil {
		if cerr := q.updateBotLastSeenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBotLastSeenStmt: %w", cerr)
		}
	}
	if q.updateJobCancelStmt != nil {
		if cerr := q.updateJobCancelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateJobCancelStmt: %w", cerr)
		}
	}
	if q.updateJobChargeStmt != nil {
		if cerr := q.updateJobChargeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateJobChargeStmt: %w", cerr)
		}
	}
	if q.updateJobDeliverStmt != nil {
		if cerr := q.updateJobDeliverStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateJobDeliverStmt: %w", cerr)
		}
	}
	if q.updateJobExpireStmt != nil {
		if cerr := q.updateJobExpireStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateJobExpireStmt: %w", cerr)
		}
	}
	if q.updateJobMarkPaidStmt != nil {
		if cerr := q.updateJobMarkPaidStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateJobMarkPaidStmt: %w", cerr)
		}
	}
	if q.updateOfferCancelStmt != nil {
		if cerr := q.updateOfferCancelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOfferCancelStmt: %w", cerr)
		}
	}
	if q.updateOfferExpireStmt != nil {
		if cerr := q.updateOfferExpireStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOfferExpireStmt: %w", cerr)
		}
	}
	if q.upsertPollAckStmt != nil {
		if cerr := q.upsertPollAckStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertPollAckStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                    DBTX
	tx                                    *sql.Tx
	countActiveJobsByChargeAddressStmt    *sql.Stmt
	countNonceStmt                        *sql.Stmt
	createBotStmt                         *sql.Stmt
	createEventStmt                       *sql.Stmt
	createJobStmt                         *sql.Stmt
	createOfferStmt                       *sql.Stmt
	createPayloadStmt                     *sql.Stmt
	deleteEventsBeforeStmt                *sql.Stmt
	deleteIdempotencyBeforeStmt           *sql.Stmt
	deleteNoncesBeforeStmt                *sql.Stmt
	deletePayloadsBeforeStmt              *sql.Stmt
	getBotStmt                            *sql.Stmt
	getIdempotencyStmt                    *sql.Stmt
	getJobStmt                            *sql.Stmt
	getMinEventIDStmt                     *sql.Stmt
	getOfferStmt                          *sql.Stmt
	getPayloadStmt                        *sql.Stmt
	getPollAckStmt                        *sql.Stmt
	insertIdempotencyStmt                 *sql.Stmt
	insertNonceStmt                       *sql.Stmt
	insertOfferTagStmt                    *sql.Stmt
	listEventsAfterIDStmt                 *sql.Stmt
	listJobsByBuyerNewestStmt             *sql.Stmt
	listJobsByBuyerNewestAfterStmt        *sql.Stmt
	listJobsByBuyerSinceStmt              *sql.Stmt
	listJobsByBuyerSinceAfterStmt         *sql.Stmt
	listJobsBySellerNewestStmt            *sql.Stmt
	listJobsBySellerNewestAfterStmt       *sql.Stmt
	listJobsBySellerSinceStmt             *sql.Stmt
	listJobsBySellerSinceAfterStmt        *sql.Stmt
	listOfferIDsByTagStmt                 *sql.Stmt
	listOfferTagsStmt                     *sql.Stmt
	listOffersNewestStmt                  *sql.Stmt
	listOffersNewestAfterStmt             *sql.Stmt
	listPayloadMetadataAllStmt            *sql.Stmt
	listPayloadMetadataAllAfterStmt       *sql.Stmt
	listPayloadMetadataFetchedStmt        *sql.Stmt
	listPayloadMetadataFetchedAfterStmt   *sql.Stmt
	listPayloadMetadataUnfetchedStmt      *sql.Stmt
	listPayloadMetadataUnfetchedAfterStmt *sql.Stmt
	markPayloadFetchedStmt                *sql.Stmt
	updateBotLastSeenStmt                 *sql.Stmt
	updateJobCancelStmt                   *sql.Stmt
	updateJobChargeStmt                   *sql.Stmt
	updateJobDeliverStmt                  *sql.Stmt
	updateJobExpireStmt                   *sql.Stmt
	updateJobMarkPaidStmt                 *sql.Stmt
	updateOfferCancelStmt                 *sql.Stmt
	updateOfferExpireStmt                 *sql.Stmt
	upsertPollAckStmt                     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                    tx,
		tx:                                    tx,
		countActiveJobsByChargeAddressStmt:    q.countActiveJobsByChargeAddressStmt,
		countNonceStmt:                        q.countNonceStmt,
		createBotStmt:                         q.createBotStmt,
		createEventStmt:                       q.createEventStmt,
		createJobStmt:                         q.createJobStmt,
		createOfferStmt:                       q.createOfferStmt,
		createPayloadStmt:                     q.createPayloadStmt,
		deleteEventsBeforeStmt:                q.deleteEventsBeforeStmt,
		deleteIdempotencyBeforeStmt:           q.deleteIdempotencyBeforeStmt,
		deleteNoncesBeforeStmt:                q.deleteNoncesBeforeStmt,
		deletePayloadsBeforeStmt:              q.deletePayloadsBeforeStmt,
		getBotStmt:                            q.getBotStmt,
		getIdempotencyStmt:                    q.getIdempotencyStmt,
		getJobStmt:                            q.getJobStmt,
		getMinEventIDStmt:                     q.getMinEventIDStmt,
		getOfferStmt:                          q.getOfferStmt,
		getPayloadStmt:                        q.getPayloadStmt,
		getPollAckStmt:                        q.getPollAckStmt,
		insertIdempotencyStmt:                 q.insertIdempotencyStmt,
		insertNonceStmt:                       q.insertNonceStmt,
		insertOfferTagStmt:                    q.insertOfferTagStmt,
		listEventsAfterIDStmt:                 q.listEventsAfterIDStmt,
		listJobsByBuyerNewestStmt:             q.listJobsByBuyerNewestStmt,
		listJobsByBuyerNewestAfterStmt:        q.listJobsByBuyerNewestAfterStmt,
		listJobsByBuyerSinceStmt:              q.listJobsByBuyerSinceStmt,
		listJobsByBuyerSinceAfterStmt:         q.listJobsByBuyerSinceAfterStmt,
		listJobsBySellerNewestStmt:            q.listJobsBySellerNewestStmt,
		listJobsBySellerNewestAfterStmt:       q.listJobsBySellerNewestAfterStmt,
		listJobsBySellerSinceStmt:             q.listJobsBySellerSinceStmt,
		listJobsBySellerSinceAfterStmt:        q.listJobsBySellerSinceAfterStmt,
		listOfferIDsByTagStmt:                 q.listOfferIDsByTagStmt,
		listOfferTagsStmt:                     q.listOfferTagsStmt,
		listOffersNewestStmt:                  q.listOffersNewestStmt,
		listOffersNewestAfterStmt:             q.listOffersNewestAfterStmt,
		listPayloadMetadataAllStmt:            q.listPayloadMetadataAllStmt,
		listPayloadMetadataAllAfterStmt:       q.listPayloadMetadataAllAfterStmt,
		listPayloadMetadataFetchedStmt:        q.listPayloadMetadataFetchedStmt,
		listPayloadMetadataFetchedAfterStmt:   q.listPayloadMetadataFetchedAfterStmt,
		listPayloadMetadataUnfetchedStmt:      q.listPayloadMetadataUnfetchedStmt,
		listPayloadMetadataUnfetchedAfterStmt: q.listPayloadMetadataUnfetchedAfterStmt,
		markPayloadFetchedStmt:                q.markPayloadFetchedStmt,
		updateBotLastSeenStmt:                 q.updateBotLastSeenStmt,
		updateJobCancelStmt:                   q.updateJobCancelStmt,
		updateJobChargeStmt:                   q.updateJobChargeStmt,
		updateJobDeliverStmt:                  q.updateJobDeliverStmt,
		updateJobExpireStmt:                   q.updateJobExpireStmt,
		updateJobMarkPaidStmt:                 q.updateJobMarkPaidStmt,
		updateOfferCancelStmt:                 q.updateOfferCancelStmt,
		updateOfferExpireStmt:                 q.updateOfferExpireStmt,
		upsertPollAckStmt:                     q.upsertPollAckStmt,
	}
}
