// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type AdminAuditLog struct {
	ID               int64          `json:"id"`
	Action           string         `json:"action"`
	TargetType       string         `json:"target_type"`
	TargetID         string         `json:"target_id"`
	Reason           string         `json:"reason"`
	Note             sql.NullString `json:"note"`
	RequestID        sql.NullString `json:"request_id"`
	TokenFingerprint sql.NullString `json:"token_fingerprint"`
	RemoteAddr       sql.NullString `json:"remote_addr"`
	UserAgent        sql.NullString `json:"user_agent"`
	BeforeJson       sql.NullString `json:"before_json"`
	AfterJson        sql.NullString `json:"after_json"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Bot struct {
	BotID                  string         `json:"bot_id"`
	BotName                sql.NullString `json:"bot_name"`
	SigningPubkeyEd25519   string         `json:"signing_pubkey_ed25519"`
	EncryptionPubkeyX25519 string         `json:"encryption_pubkey_x25519"`
	SigningKid             string         `json:"signing_kid"`
	EncryptionKid          string         `json:"encryption_kid"`
	CreatedAt              time.Time      `json:"created_at"`
	LastSeenAt             sql.NullTime   `json:"last_seen_at"`
	RevokedAt              sql.NullTime   `json:"revoked_at"`
}

type Event struct {
	EventID        int64     `json:"event_id"`
	RecipientBotID string    `json:"recipient_bot_id"`
	EventType      string    `json:"event_type"`
	DataJson       string    `json:"data_json"`
	CreatedAt      time.Time `json:"created_at"`
}

type IdempotencyKey struct {
	BotID           string    `json:"bot_id"`
	Endpoint        string    `json:"endpoint"`
	IdempotencyKey  string    `json:"idempotency_key"`
	RequestHash     string    `json:"request_hash"`
	ResponseCode    int64     `json:"response_code"`
	ResponseBody    string    `json:"response_body"`
	ResponseHeaders string    `json:"response_headers"`
	CreatedAt       time.Time `json:"created_at"`
}

type Job struct {
	JobID             string         `json:"job_id"`
	OfferID           string         `json:"offer_id"`
	BuyerBotID        string         `json:"buyer_bot_id"`
	SellerBotID       string         `json:"seller_bot_id"`
	Status            string         `json:"status"`
	PriceRaw          string         `json:"price_raw"`
	TurnaroundSeconds int64          `json:"turnaround_seconds"`
	CreatedAt         time.Time      `json:"created_at"`
	JobExpiresAt      time.Time      `json:"job_expires_at"`
	RequestPayloadID  string         `json:"request_payload_id"`
	ChargeID          sql.NullString `json:"charge_id"`
	ChargeAddress     sql.NullString `json:"charge_address"`
	ChargeAmountRaw   sql.NullString `json:"charge_amount_raw"`
	ChargeExpiresAt   sql.NullTime   `json:"charge_expires_at"`
	ChargeSigEd25519  sql.NullString `json:"charge_sig_ed25519"`
	PaidAt            sql.NullTime   `json:"paid_at"`
	DeliveredAt       sql.NullTime   `json:"delivered_at"`
	CancelledAt       sql.NullTime   `json:"cancelled_at"`
	ExpiredAt         sql.NullTime   `json:"expired_at"`
	PaymentVerifier   sql.NullString `json:"payment_verifier"`
	PaymentBlockHash  sql.NullString `json:"payment_block_hash"`
	PaymentObservedAt sql.NullTime   `json:"payment_observed_at"`
	AmountRawReceived sql.NullString `json:"amount_raw_received"`
}

type Nonce struct {
	BotID     string    `json:"bot_id"`
	Nonce     string    `json:"nonce"`
	CreatedAt time.Time `json:"created_at"`
}

type Offer struct {
	OfferID           string         `json:"offer_id"`
	SellerBotID       string         `json:"seller_bot_id"`
	Title             string         `json:"title"`
	Description       string         `json:"description"`
	TagsJson          string         `json:"tags_json"`
	PriceRaw          string         `json:"price_raw"`
	TurnaroundSeconds int64          `json:"turnaround_seconds"`
	CreatedAt         time.Time      `json:"created_at"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
	Status            string         `json:"status"`
	CancelledAt       sql.NullTime   `json:"cancelled_at"`
	RequestSchemaHint sql.NullString `json:"request_schema_hint"`
}

type OfferTag struct {
	OfferID string `json:"offer_id"`
	Tag     string `json:"tag"`
}

type OffersFt struct {
	OfferID     string `json:"offer_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
}

type Payload struct {
	PayloadID      string       `json:"payload_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
	JobID          string       `json:"job_id"`
	SenderBotID    string       `json:"sender_bot_id"`
	PayloadKind    string       `json:"payload_kind"`
	EncAlg         string       `json:"enc_alg"`
	RecipientKid   string       `json:"recipient_kid"`
	CiphertextB64  string       `json:"ciphertext_b64"`
	CreatedAt      time.Time    `json:"created_at"`
	FetchedAt      sql.NullTime `json:"fetched_at"`
}

type PollAck struct {
	RecipientBotID   string    `json:"recipient_bot_id"`
	LastAckedEventID int64     `json:"last_acked_event_id"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type StreamAck struct {
	StreamKey string    `json:"stream_key"`
	AckCursor int64     `json:"ack_cursor"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StreamEvent struct {
	StreamKey   string    `json:"stream_key"`
	Cursor      int64     `json:"cursor"`
	EventType   string    `json:"event_type"`
	CreatedAt   time.Time `json:"created_at"`
	PayloadJson string    `json:"payload_json"`
}
