// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const cancelJobsByBot = `-- name: CancelJobsByBot :many
UPDATE jobs
SET status = 'CANCELLED',
	cancelled_at = ?1
WHERE (buyer_bot_id = ?2 OR seller_bot_id = ?2)
	AND status IN ('REQUESTED', 'CHARGE_CREATED')
RETURNING job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received
`

type CancelJobsByBotParams struct {
	CancelledAt sql.NullTime `json:"cancelled_at"`
	BotID       string       `json:"bot_id"`
}

func (q *Queries) CancelJobsByBot(ctx context.Context, arg CancelJobsByBotParams) ([]Job, error) {
	rows, err := q.query(ctx, q.cancelJobsByBotStmt, cancelJobsByBot, arg.CancelledAt, arg.BotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelOffersBySeller = `-- name: CancelOffersBySeller :many
UPDATE offers
SET status = 'CANCELLED',
	cancelled_at = ?1
WHERE seller_bot_id = ?2
	AND status IN ('ACTIVE', 'PAUSED')
RETURNING offer_id, seller_bot_id, title, description, tags_json, price_raw, turnaround_seconds, created_at, expires_at, status, cancelled_at, request_schema_hint
`

type CancelOffersBySellerParams struct {
	CancelledAt sql.NullTime `json:"cancelled_at"`
	SellerBotID string       `json:"seller_bot_id"`
}

func (q *Queries) CancelOffersBySeller(ctx context.Context, arg CancelOffersBySellerParams) ([]Offer, error) {
	rows, err := q.query(ctx, q.cancelOffersBySellerStmt, cancelOffersBySeller, arg.CancelledAt, arg.SellerBotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.OfferID,
			&i.SellerBotID,
			&i.Title,
			&i.Description,
			&i.TagsJson,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.CancelledAt,
			&i.RequestSchemaHint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveJobsByChargeAddress = `-- name: CountActiveJobsByChargeAddress :one
SELECT COUNT(1) FROM jobs
WHERE seller_bot_id = ?1
	AND charge_address = ?2
	AND status IN ('REQUESTED', 'CHARGE_CREATED', 'PAID')
`

type CountActiveJobsByChargeAddressParams struct {
	SellerBotID   string         `json:"seller_bot_id"`
	ChargeAddress sql.NullString `json:"charge_address"`
}

func (q *Queries) CountActiveJobsByChargeAddress(ctx context.Context, arg CountActiveJobsByChargeAddressParams) (int64, error) {
	row := q.queryRow(ctx, q.countActiveJobsByChargeAddressStmt, countActiveJobsByChargeAddress, arg.SellerBotID, arg.ChargeAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNonce = `-- name: CountNonce :one
SELECT COUNT(1) FROM nonces
WHERE bot_id = ?1
	AND nonce = ?2
`

type CountNonceParams struct {
	BotID string `json:"bot_id"`
	Nonce string `json:"nonce"`
}

func (q *Queries) CountNonce(ctx context.Context, arg CountNonceParams) (int64, error) {
	row := q.queryRow(ctx, q.countNonceStmt, countNonce, arg.BotID, arg.Nonce)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBot = `-- name: CreateBot :exec

INSERT INTO bots (
	bot_id,
	signing_pubkey_ed25519,
	encryption_pubkey_x25519,
	signing_kid,
	encryption_kid,
	created_at,
	last_seen_at
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7
)
`

type CreateBotParams struct {
	BotID                  string       `json:"bot_id"`
	SigningPubkeyEd25519   string       `json:"signing_pubkey_ed25519"`
	EncryptionPubkeyX25519 string       `json:"encryption_pubkey_x25519"`
	SigningKid             string       `json:"signing_kid"`
	EncryptionKid          string       `json:"encryption_kid"`
	CreatedAt              time.Time    `json:"created_at"`
	LastSeenAt             sql.NullTime `json:"last_seen_at"`
}

// NanoBazaar Relay v0.2 queries
// Bots
func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) error {
	_, err := q.exec(ctx, q.createBotStmt, createBot,
		arg.BotID,
		arg.SigningPubkeyEd25519,
		arg.EncryptionPubkeyX25519,
		arg.SigningKid,
		arg.EncryptionKid,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (
	recipient_bot_id,
	event_type,
	data_json,
	created_at
) VALUES (
	?1,
	?2,
	?3,
	?4
)
`

type CreateEventParams struct {
	RecipientBotID string    `json:"recipient_bot_id"`
	EventType      string    `json:"event_type"`
	DataJson       string    `json:"data_json"`
	CreatedAt      time.Time `json:"created_at"`
}

// Events
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.exec(ctx, q.createEventStmt, createEvent,
		arg.RecipientBotID,
		arg.EventType,
		arg.DataJson,
		arg.CreatedAt,
	)
	return err
}

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (
	job_id,
	offer_id,
	buyer_bot_id,
	seller_bot_id,
	status,
	price_raw,
	turnaround_seconds,
	created_at,
	job_expires_at,
	request_payload_id,
	charge_id,
	charge_address,
	charge_amount_raw,
	charge_expires_at,
	charge_sig_ed25519,
	paid_at,
	delivered_at,
	cancelled_at,
	expired_at,
	payment_verifier,
	payment_block_hash,
	payment_observed_at,
	amount_raw_received
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10,
	?11,
	?12,
	?13,
	?14,
	?15,
	?16,
	?17,
	?18,
	?19,
	?20,
	?21,
	?22,
	?23
)
`

type CreateJobParams struct {
	JobID             string         `json:"job_id"`
	OfferID           string         `json:"offer_id"`
	BuyerBotID        string         `json:"buyer_bot_id"`
	SellerBotID       string         `json:"seller_bot_id"`
	Status            string         `json:"status"`
	PriceRaw          string         `json:"price_raw"`
	TurnaroundSeconds int64          `json:"turnaround_seconds"`
	CreatedAt         time.Time      `json:"created_at"`
	JobExpiresAt      time.Time      `json:"job_expires_at"`
	RequestPayloadID  string         `json:"request_payload_id"`
	ChargeID          sql.NullString `json:"charge_id"`
	ChargeAddress     sql.NullString `json:"charge_address"`
	ChargeAmountRaw   sql.NullString `json:"charge_amount_raw"`
	ChargeExpiresAt   sql.NullTime   `json:"charge_expires_at"`
	ChargeSigEd25519  sql.NullString `json:"charge_sig_ed25519"`
	PaidAt            sql.NullTime   `json:"paid_at"`
	DeliveredAt       sql.NullTime   `json:"delivered_at"`
	CancelledAt       sql.NullTime   `json:"cancelled_at"`
	ExpiredAt         sql.NullTime   `json:"expired_at"`
	PaymentVerifier   sql.NullString `json:"payment_verifier"`
	PaymentBlockHash  sql.NullString `json:"payment_block_hash"`
	PaymentObservedAt sql.NullTime   `json:"payment_observed_at"`
	AmountRawReceived sql.NullString `json:"amount_raw_received"`
}

// Jobs
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.exec(ctx, q.createJobStmt, createJob,
		arg.JobID,
		arg.OfferID,
		arg.BuyerBotID,
		arg.SellerBotID,
		arg.Status,
		arg.PriceRaw,
		arg.TurnaroundSeconds,
		arg.CreatedAt,
		arg.JobExpiresAt,
		arg.RequestPayloadID,
		arg.ChargeID,
		arg.ChargeAddress,
		arg.ChargeAmountRaw,
		arg.ChargeExpiresAt,
		arg.ChargeSigEd25519,
		arg.PaidAt,
		arg.DeliveredAt,
		arg.CancelledAt,
		arg.ExpiredAt,
		arg.PaymentVerifier,
		arg.PaymentBlockHash,
		arg.PaymentObservedAt,
		arg.AmountRawReceived,
	)
	return err
}

const createOffer = `-- name: CreateOffer :exec
INSERT INTO offers (
	offer_id,
	seller_bot_id,
	title,
	description,
	tags_json,
	price_raw,
	turnaround_seconds,
	created_at,
	expires_at,
	status,
	cancelled_at,
	request_schema_hint
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10,
	?11,
	?12
)
`

type CreateOfferParams struct {
	OfferID           string         `json:"offer_id"`
	SellerBotID       string         `json:"seller_bot_id"`
	Title             string         `json:"title"`
	Description       string         `json:"description"`
	TagsJson          string         `json:"tags_json"`
	PriceRaw          string         `json:"price_raw"`
	TurnaroundSeconds int64          `json:"turnaround_seconds"`
	CreatedAt         time.Time      `json:"created_at"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
	Status            string         `json:"status"`
	CancelledAt       sql.NullTime   `json:"cancelled_at"`
	RequestSchemaHint sql.NullString `json:"request_schema_hint"`
}

// Offers
func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) error {
	_, err := q.exec(ctx, q.createOfferStmt, createOffer,
		arg.OfferID,
		arg.SellerBotID,
		arg.Title,
		arg.Description,
		arg.TagsJson,
		arg.PriceRaw,
		arg.TurnaroundSeconds,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Status,
		arg.CancelledAt,
		arg.RequestSchemaHint,
	)
	return err
}

const createPayload = `-- name: CreatePayload :exec
INSERT INTO payloads (
	payload_id,
	recipient_bot_id,
	job_id,
	sender_bot_id,
	payload_kind,
	enc_alg,
	recipient_kid,
	ciphertext_b64,
	created_at,
	fetched_at
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10
)
`

type CreatePayloadParams struct {
	PayloadID      string       `json:"payload_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
	JobID          string       `json:"job_id"`
	SenderBotID    string       `json:"sender_bot_id"`
	PayloadKind    string       `json:"payload_kind"`
	EncAlg         string       `json:"enc_alg"`
	RecipientKid   string       `json:"recipient_kid"`
	CiphertextB64  string       `json:"ciphertext_b64"`
	CreatedAt      time.Time    `json:"created_at"`
	FetchedAt      sql.NullTime `json:"fetched_at"`
}

// Payloads
func (q *Queries) CreatePayload(ctx context.Context, arg CreatePayloadParams) error {
	_, err := q.exec(ctx, q.createPayloadStmt, createPayload,
		arg.PayloadID,
		arg.RecipientBotID,
		arg.JobID,
		arg.SenderBotID,
		arg.PayloadKind,
		arg.EncAlg,
		arg.RecipientKid,
		arg.CiphertextB64,
		arg.CreatedAt,
		arg.FetchedAt,
	)
	return err
}

const createStreamEvent = `-- name: CreateStreamEvent :one
INSERT INTO stream_events (
	stream_key,
	cursor,
	event_type,
	created_at,
	payload_json
) VALUES (
	?1,
	(SELECT COALESCE(MAX(cursor), 0) + 1 FROM stream_events WHERE stream_key = ?1),
	?2,
	?3,
	?4
)
RETURNING cursor
`

type CreateStreamEventParams struct {
	StreamKey   string    `json:"stream_key"`
	EventType   string    `json:"event_type"`
	CreatedAt   time.Time `json:"created_at"`
	PayloadJson string    `json:"payload_json"`
}

// Stream events
func (q *Queries) CreateStreamEvent(ctx context.Context, arg CreateStreamEventParams) (int64, error) {
	row := q.queryRow(ctx, q.createStreamEventStmt, createStreamEvent,
		arg.StreamKey,
		arg.EventType,
		arg.CreatedAt,
		arg.PayloadJson,
	)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const deleteEventsBefore = `-- name: DeleteEventsBefore :exec
DELETE FROM events
WHERE created_at < ?1
`

func (q *Queries) DeleteEventsBefore(ctx context.Context, cutoff time.Time) error {
	_, err := q.exec(ctx, q.deleteEventsBeforeStmt, deleteEventsBefore, cutoff)
	return err
}

const deleteIdempotencyBefore = `-- name: DeleteIdempotencyBefore :exec
DELETE FROM idempotency_keys
WHERE created_at < ?1
`

func (q *Queries) DeleteIdempotencyBefore(ctx context.Context, cutoff time.Time) error {
	_, err := q.exec(ctx, q.deleteIdempotencyBeforeStmt, deleteIdempotencyBefore, cutoff)
	return err
}

const deleteJobsTerminalBefore = `-- name: DeleteJobsTerminalBefore :exec
DELETE FROM jobs
WHERE status IN ('CANCELLED', 'EXPIRED', 'DELIVERED')
	AND (
		(status = 'CANCELLED' AND cancelled_at < ?1)
		OR (status = 'EXPIRED' AND expired_at < ?1)
		OR (status = 'DELIVERED' AND delivered_at < ?1)
	)
`

func (q *Queries) DeleteJobsTerminalBefore(ctx context.Context, cutoff sql.NullTime) error {
	_, err := q.exec(ctx, q.deleteJobsTerminalBeforeStmt, deleteJobsTerminalBefore, cutoff)
	return err
}

const deleteNoncesBefore = `-- name: DeleteNoncesBefore :exec
DELETE FROM nonces
WHERE created_at < ?1
`

func (q *Queries) DeleteNoncesBefore(ctx context.Context, cutoff time.Time) error {
	_, err := q.exec(ctx, q.deleteNoncesBeforeStmt, deleteNoncesBefore, cutoff)
	return err
}

const deleteOffersBefore = `-- name: DeleteOffersBefore :exec
DELETE FROM offers
WHERE created_at < ?1
`

func (q *Queries) DeleteOffersBefore(ctx context.Context, cutoff time.Time) error {
	_, err := q.exec(ctx, q.deleteOffersBeforeStmt, deleteOffersBefore, cutoff)
	return err
}

const deletePayloadsBefore = `-- name: DeletePayloadsBefore :exec
DELETE FROM payloads
WHERE created_at < ?1
`

func (q *Queries) DeletePayloadsBefore(ctx context.Context, cutoff time.Time) error {
	_, err := q.exec(ctx, q.deletePayloadsBeforeStmt, deletePayloadsBefore, cutoff)
	return err
}

const deletePayloadsFetchedBefore = `-- name: DeletePayloadsFetchedBefore :exec
DELETE FROM payloads
WHERE fetched_at IS NOT NULL
	AND fetched_at < ?1
`

func (q *Queries) DeletePayloadsFetchedBefore(ctx context.Context, cutoff sql.NullTime) error {
	_, err := q.exec(ctx, q.deletePayloadsFetchedBeforeStmt, deletePayloadsFetchedBefore, cutoff)
	return err
}

const deleteStreamEventsAckedBefore = `-- name: DeleteStreamEventsAckedBefore :exec
DELETE FROM stream_events
WHERE created_at < ?1
	AND cursor <= COALESCE((SELECT ack_cursor FROM stream_acks WHERE stream_key = stream_events.stream_key), -1)
`

func (q *Queries) DeleteStreamEventsAckedBefore(ctx context.Context, cutoff time.Time) error {
	_, err := q.exec(ctx, q.deleteStreamEventsAckedBeforeStmt, deleteStreamEventsAckedBefore, cutoff)
	return err
}

const getBot = `-- name: GetBot :one
SELECT bot_id, signing_pubkey_ed25519, encryption_pubkey_x25519, signing_kid, encryption_kid, created_at, last_seen_at, revoked_at FROM bots WHERE bot_id = ?1
`

func (q *Queries) GetBot(ctx context.Context, botID string) (Bot, error) {
	row := q.queryRow(ctx, q.getBotStmt, getBot, botID)
	var i Bot
	err := row.Scan(
		&i.BotID,
		&i.SigningPubkeyEd25519,
		&i.EncryptionPubkeyX25519,
		&i.SigningKid,
		&i.EncryptionKid,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getEventCreatedAt = `-- name: GetEventCreatedAt :one
SELECT created_at FROM events
WHERE recipient_bot_id = ?1
	AND event_id = ?2
`

type GetEventCreatedAtParams struct {
	RecipientBotID string `json:"recipient_bot_id"`
	EventID        int64  `json:"event_id"`
}

func (q *Queries) GetEventCreatedAt(ctx context.Context, arg GetEventCreatedAtParams) (time.Time, error) {
	row := q.queryRow(ctx, q.getEventCreatedAtStmt, getEventCreatedAt, arg.RecipientBotID, arg.EventID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT bot_id, endpoint, idempotency_key, request_hash, response_code, response_body, response_headers, created_at FROM idempotency_keys
WHERE bot_id = ?1
	AND endpoint = ?2
	AND idempotency_key = ?3
`

type GetIdempotencyParams struct {
	BotID          string `json:"bot_id"`
	Endpoint       string `json:"endpoint"`
	IdempotencyKey string `json:"idempotency_key"`
}

// Idempotency
func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyKey, error) {
	row := q.queryRow(ctx, q.getIdempotencyStmt, getIdempotency, arg.BotID, arg.Endpoint, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.BotID,
		&i.Endpoint,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.ResponseHeaders,
		&i.CreatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs WHERE job_id = ?1
`

func (q *Queries) GetJob(ctx context.Context, jobID string) (Job, error) {
	row := q.queryRow(ctx, q.getJobStmt, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.OfferID,
		&i.BuyerBotID,
		&i.SellerBotID,
		&i.Status,
		&i.PriceRaw,
		&i.TurnaroundSeconds,
		&i.CreatedAt,
		&i.JobExpiresAt,
		&i.RequestPayloadID,
		&i.ChargeID,
		&i.ChargeAddress,
		&i.ChargeAmountRaw,
		&i.ChargeExpiresAt,
		&i.ChargeSigEd25519,
		&i.PaidAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.ExpiredAt,
		&i.PaymentVerifier,
		&i.PaymentBlockHash,
		&i.PaymentObservedAt,
		&i.AmountRawReceived,
	)
	return i, err
}

const getMinEventID = `-- name: GetMinEventID :one
SELECT MIN(event_id) FROM events
WHERE recipient_bot_id = ?1
`

func (q *Queries) GetMinEventID(ctx context.Context, recipientBotID string) (interface{}, error) {
	row := q.queryRow(ctx, q.getMinEventIDStmt, getMinEventID, recipientBotID)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getOffer = `-- name: GetOffer :one
SELECT offer_id, seller_bot_id, title, description, tags_json, price_raw, turnaround_seconds, created_at, expires_at, status, cancelled_at, request_schema_hint FROM offers WHERE offer_id = ?1
`

func (q *Queries) GetOffer(ctx context.Context, offerID string) (Offer, error) {
	row := q.queryRow(ctx, q.getOfferStmt, getOffer, offerID)
	var i Offer
	err := row.Scan(
		&i.OfferID,
		&i.SellerBotID,
		&i.Title,
		&i.Description,
		&i.TagsJson,
		&i.PriceRaw,
		&i.TurnaroundSeconds,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CancelledAt,
		&i.RequestSchemaHint,
	)
	return i, err
}

const getPayload = `-- name: GetPayload :one
SELECT payload_id, recipient_bot_id, job_id, sender_bot_id, payload_kind, enc_alg, recipient_kid, ciphertext_b64, created_at, fetched_at FROM payloads
WHERE payload_id = ?1
	AND recipient_bot_id = ?2
`

type GetPayloadParams struct {
	PayloadID      string `json:"payload_id"`
	RecipientBotID string `json:"recipient_bot_id"`
}

func (q *Queries) GetPayload(ctx context.Context, arg GetPayloadParams) (Payload, error) {
	row := q.queryRow(ctx, q.getPayloadStmt, getPayload, arg.PayloadID, arg.RecipientBotID)
	var i Payload
	err := row.Scan(
		&i.PayloadID,
		&i.RecipientBotID,
		&i.JobID,
		&i.SenderBotID,
		&i.PayloadKind,
		&i.EncAlg,
		&i.RecipientKid,
		&i.CiphertextB64,
		&i.CreatedAt,
		&i.FetchedAt,
	)
	return i, err
}

const getPayloadRecipient = `-- name: GetPayloadRecipient :one
SELECT recipient_bot_id FROM payloads
WHERE payload_id = ?1
LIMIT 1
`

func (q *Queries) GetPayloadRecipient(ctx context.Context, payloadID string) (string, error) {
	row := q.queryRow(ctx, q.getPayloadRecipientStmt, getPayloadRecipient, payloadID)
	var recipient_bot_id string
	err := row.Scan(&recipient_bot_id)
	return recipient_bot_id, err
}

const getPollAck = `-- name: GetPollAck :one
SELECT recipient_bot_id, last_acked_event_id, updated_at FROM poll_acks
WHERE recipient_bot_id = ?1
`

// Poll acks
func (q *Queries) GetPollAck(ctx context.Context, recipientBotID string) (PollAck, error) {
	row := q.queryRow(ctx, q.getPollAckStmt, getPollAck, recipientBotID)
	var i PollAck
	err := row.Scan(&i.RecipientBotID, &i.LastAckedEventID, &i.UpdatedAt)
	return i, err
}

const getStreamAck = `-- name: GetStreamAck :one
SELECT stream_key, ack_cursor, updated_at FROM stream_acks
WHERE stream_key = ?1
`

// Stream acks
func (q *Queries) GetStreamAck(ctx context.Context, streamKey string) (StreamAck, error) {
	row := q.queryRow(ctx, q.getStreamAckStmt, getStreamAck, streamKey)
	var i StreamAck
	err := row.Scan(&i.StreamKey, &i.AckCursor, &i.UpdatedAt)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO idempotency_keys (
	bot_id,
	endpoint,
	idempotency_key,
	request_hash,
	response_code,
	response_body,
	response_headers,
	created_at
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8
)
`

type InsertIdempotencyParams struct {
	BotID           string    `json:"bot_id"`
	Endpoint        string    `json:"endpoint"`
	IdempotencyKey  string    `json:"idempotency_key"`
	RequestHash     string    `json:"request_hash"`
	ResponseCode    int64     `json:"response_code"`
	ResponseBody    string    `json:"response_body"`
	ResponseHeaders string    `json:"response_headers"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.exec(ctx, q.insertIdempotencyStmt, insertIdempotency,
		arg.BotID,
		arg.Endpoint,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.ResponseHeaders,
		arg.CreatedAt,
	)
	return err
}

const insertNonce = `-- name: InsertNonce :exec
INSERT INTO nonces (
	bot_id,
	nonce,
	created_at
) VALUES (
	?1,
	?2,
	?3
)
`

type InsertNonceParams struct {
	BotID     string    `json:"bot_id"`
	Nonce     string    `json:"nonce"`
	CreatedAt time.Time `json:"created_at"`
}

// Nonces (replay protection)
func (q *Queries) InsertNonce(ctx context.Context, arg InsertNonceParams) error {
	_, err := q.exec(ctx, q.insertNonceStmt, insertNonce, arg.BotID, arg.Nonce, arg.CreatedAt)
	return err
}

const insertOfferTag = `-- name: InsertOfferTag :exec
INSERT INTO offer_tags (
	offer_id,
	tag
) VALUES (
	?1,
	?2
)
`

type InsertOfferTagParams struct {
	OfferID string `json:"offer_id"`
	Tag     string `json:"tag"`
}

func (q *Queries) InsertOfferTag(ctx context.Context, arg InsertOfferTagParams) error {
	_, err := q.exec(ctx, q.insertOfferTagStmt, insertOfferTag, arg.OfferID, arg.Tag)
	return err
}

const listEventsAfterID = `-- name: ListEventsAfterID :many
SELECT event_id,
	recipient_bot_id,
	event_type,
	data_json,
	created_at
FROM events
WHERE recipient_bot_id = ?1
	AND event_id > ?2
ORDER BY event_id ASC
LIMIT ?3
`

type ListEventsAfterIDParams struct {
	RecipientBotID string `json:"recipient_bot_id"`
	SinceEventID   int64  `json:"since_event_id"`
	Limit          int64  `json:"limit"`
}

func (q *Queries) ListEventsAfterID(ctx context.Context, arg ListEventsAfterIDParams) ([]Event, error) {
	rows, err := q.query(ctx, q.listEventsAfterIDStmt, listEventsAfterID, arg.RecipientBotID, arg.SinceEventID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.RecipientBotID,
			&i.EventType,
			&i.DataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfterIDByTypes = `-- name: ListEventsAfterIDByTypes :many
SELECT event_id,
	recipient_bot_id,
	event_type,
	data_json,
	created_at
FROM events
WHERE recipient_bot_id = ?1
	AND event_id > ?2
	AND event_type IN (/*SLICE:event_types*/?)
ORDER BY event_id ASC
LIMIT ?4
`

type ListEventsAfterIDByTypesParams struct {
	RecipientBotID string   `json:"recipient_bot_id"`
	SinceEventID   int64    `json:"since_event_id"`
	EventTypes     []string `json:"event_types"`
	Limit          int64    `json:"limit"`
}

func (q *Queries) ListEventsAfterIDByTypes(ctx context.Context, arg ListEventsAfterIDByTypesParams) ([]Event, error) {
	query := listEventsAfterIDByTypes
	var queryParams []interface{}
	queryParams = append(queryParams, arg.RecipientBotID)
	queryParams = append(queryParams, arg.SinceEventID)
	if len(arg.EventTypes) > 0 {
		for _, v := range arg.EventTypes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:event_types*/?", strings.Repeat(",?", len(arg.EventTypes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:event_types*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.RecipientBotID,
			&i.EventType,
			&i.DataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByBuyerNewest = `-- name: ListJobsByBuyerNewest :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE buyer_bot_id = ?1
ORDER BY created_at DESC, job_id DESC
LIMIT ?2
`

type ListJobsByBuyerNewestParams struct {
	BuyerBotID string `json:"buyer_bot_id"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListJobsByBuyerNewest(ctx context.Context, arg ListJobsByBuyerNewestParams) ([]Job, error) {
	rows, err := q.query(ctx, q.listJobsByBuyerNewestStmt, listJobsByBuyerNewest, arg.BuyerBotID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByBuyerNewestAfter = `-- name: ListJobsByBuyerNewestAfter :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE buyer_bot_id = ?1
	AND (
		created_at < ?2
		OR (created_at = ?2 AND job_id < ?3)
	)
ORDER BY created_at DESC, job_id DESC
LIMIT ?4
`

type ListJobsByBuyerNewestAfterParams struct {
	BuyerBotID      string    `json:"buyer_bot_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorJobID     string    `json:"cursor_job_id"`
	Limit           int64     `json:"limit"`
}

func (q *Queries) ListJobsByBuyerNewestAfter(ctx context.Context, arg ListJobsByBuyerNewestAfterParams) ([]Job, error) {
	rows, err := q.query(ctx, q.listJobsByBuyerNewestAfterStmt, listJobsByBuyerNewestAfter,
		arg.BuyerBotID,
		arg.CursorCreatedAt,
		arg.CursorJobID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByBuyerNewestAfterWithStatus = `-- name: ListJobsByBuyerNewestAfterWithStatus :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE buyer_bot_id = ?1
	AND status IN (/*SLICE:statuses*/?)
	AND (
		created_at < ?3
		OR (created_at = ?3 AND job_id < ?4)
	)
ORDER BY created_at DESC, job_id DESC
LIMIT ?5
`

type ListJobsByBuyerNewestAfterWithStatusParams struct {
	BuyerBotID      string    `json:"buyer_bot_id"`
	Statuses        []string  `json:"statuses"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorJobID     string    `json:"cursor_job_id"`
	Limit           int64     `json:"limit"`
}

func (q *Queries) ListJobsByBuyerNewestAfterWithStatus(ctx context.Context, arg ListJobsByBuyerNewestAfterWithStatusParams) ([]Job, error) {
	query := listJobsByBuyerNewestAfterWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BuyerBotID)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorJobID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByBuyerNewestWithStatus = `-- name: ListJobsByBuyerNewestWithStatus :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE buyer_bot_id = ?1
	AND status IN (/*SLICE:statuses*/?)
ORDER BY created_at DESC, job_id DESC
LIMIT ?3
`

type ListJobsByBuyerNewestWithStatusParams struct {
	BuyerBotID string   `json:"buyer_bot_id"`
	Statuses   []string `json:"statuses"`
	Limit      int64    `json:"limit"`
}

func (q *Queries) ListJobsByBuyerNewestWithStatus(ctx context.Context, arg ListJobsByBuyerNewestWithStatusParams) ([]Job, error) {
	query := listJobsByBuyerNewestWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BuyerBotID)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByBuyerSince = `-- name: ListJobsByBuyerSince :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE buyer_bot_id = ?1
	AND created_at >= ?2
ORDER BY created_at DESC, job_id DESC
LIMIT ?3
`

type ListJobsByBuyerSinceParams struct {
	BuyerBotID   string    `json:"buyer_bot_id"`
	CreatedSince time.Time `json:"created_since"`
	Limit        int64     `json:"limit"`
}

func (q *Queries) ListJobsByBuyerSince(ctx context.Context, arg ListJobsByBuyerSinceParams) ([]Job, error) {
	rows, err := q.query(ctx, q.listJobsByBuyerSinceStmt, listJobsByBuyerSince, arg.BuyerBotID, arg.CreatedSince, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByBuyerSinceAfter = `-- name: ListJobsByBuyerSinceAfter :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE buyer_bot_id = ?1
	AND created_at >= ?2
	AND (
		created_at < ?3
		OR (created_at = ?3 AND job_id < ?4)
	)
ORDER BY created_at DESC, job_id DESC
LIMIT ?5
`

type ListJobsByBuyerSinceAfterParams struct {
	BuyerBotID      string    `json:"buyer_bot_id"`
	CreatedSince    time.Time `json:"created_since"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorJobID     string    `json:"cursor_job_id"`
	Limit           int64     `json:"limit"`
}

func (q *Queries) ListJobsByBuyerSinceAfter(ctx context.Context, arg ListJobsByBuyerSinceAfterParams) ([]Job, error) {
	rows, err := q.query(ctx, q.listJobsByBuyerSinceAfterStmt, listJobsByBuyerSinceAfter,
		arg.BuyerBotID,
		arg.CreatedSince,
		arg.CursorCreatedAt,
		arg.CursorJobID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByBuyerSinceAfterWithStatus = `-- name: ListJobsByBuyerSinceAfterWithStatus :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE buyer_bot_id = ?1
	AND created_at >= ?2
	AND status IN (/*SLICE:statuses*/?)
	AND (
		created_at < ?4
		OR (created_at = ?4 AND job_id < ?5)
	)
ORDER BY created_at DESC, job_id DESC
LIMIT ?6
`

type ListJobsByBuyerSinceAfterWithStatusParams struct {
	BuyerBotID      string    `json:"buyer_bot_id"`
	CreatedSince    time.Time `json:"created_since"`
	Statuses        []string  `json:"statuses"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorJobID     string    `json:"cursor_job_id"`
	Limit           int64     `json:"limit"`
}

func (q *Queries) ListJobsByBuyerSinceAfterWithStatus(ctx context.Context, arg ListJobsByBuyerSinceAfterWithStatusParams) ([]Job, error) {
	query := listJobsByBuyerSinceAfterWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BuyerBotID)
	queryParams = append(queryParams, arg.CreatedSince)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorJobID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByBuyerSinceWithStatus = `-- name: ListJobsByBuyerSinceWithStatus :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE buyer_bot_id = ?1
	AND created_at >= ?2
	AND status IN (/*SLICE:statuses*/?)
ORDER BY created_at DESC, job_id DESC
LIMIT ?4
`

type ListJobsByBuyerSinceWithStatusParams struct {
	BuyerBotID   string    `json:"buyer_bot_id"`
	CreatedSince time.Time `json:"created_since"`
	Statuses     []string  `json:"statuses"`
	Limit        int64     `json:"limit"`
}

func (q *Queries) ListJobsByBuyerSinceWithStatus(ctx context.Context, arg ListJobsByBuyerSinceWithStatusParams) ([]Job, error) {
	query := listJobsByBuyerSinceWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BuyerBotID)
	queryParams = append(queryParams, arg.CreatedSince)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsBySellerNewest = `-- name: ListJobsBySellerNewest :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE seller_bot_id = ?1
ORDER BY created_at DESC, job_id DESC
LIMIT ?2
`

type ListJobsBySellerNewestParams struct {
	SellerBotID string `json:"seller_bot_id"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListJobsBySellerNewest(ctx context.Context, arg ListJobsBySellerNewestParams) ([]Job, error) {
	rows, err := q.query(ctx, q.listJobsBySellerNewestStmt, listJobsBySellerNewest, arg.SellerBotID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsBySellerNewestAfter = `-- name: ListJobsBySellerNewestAfter :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE seller_bot_id = ?1
	AND (
		created_at < ?2
		OR (created_at = ?2 AND job_id < ?3)
	)
ORDER BY created_at DESC, job_id DESC
LIMIT ?4
`

type ListJobsBySellerNewestAfterParams struct {
	SellerBotID     string    `json:"seller_bot_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorJobID     string    `json:"cursor_job_id"`
	Limit           int64     `json:"limit"`
}

func (q *Queries) ListJobsBySellerNewestAfter(ctx context.Context, arg ListJobsBySellerNewestAfterParams) ([]Job, error) {
	rows, err := q.query(ctx, q.listJobsBySellerNewestAfterStmt, listJobsBySellerNewestAfter,
		arg.SellerBotID,
		arg.CursorCreatedAt,
		arg.CursorJobID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsBySellerNewestAfterWithStatus = `-- name: ListJobsBySellerNewestAfterWithStatus :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE seller_bot_id = ?1
	AND status IN (/*SLICE:statuses*/?)
	AND (
		created_at < ?3
		OR (created_at = ?3 AND job_id < ?4)
	)
ORDER BY created_at DESC, job_id DESC
LIMIT ?5
`

type ListJobsBySellerNewestAfterWithStatusParams struct {
	SellerBotID     string    `json:"seller_bot_id"`
	Statuses        []string  `json:"statuses"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorJobID     string    `json:"cursor_job_id"`
	Limit           int64     `json:"limit"`
}

func (q *Queries) ListJobsBySellerNewestAfterWithStatus(ctx context.Context, arg ListJobsBySellerNewestAfterWithStatusParams) ([]Job, error) {
	query := listJobsBySellerNewestAfterWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SellerBotID)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorJobID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsBySellerNewestWithStatus = `-- name: ListJobsBySellerNewestWithStatus :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE seller_bot_id = ?1
	AND status IN (/*SLICE:statuses*/?)
ORDER BY created_at DESC, job_id DESC
LIMIT ?3
`

type ListJobsBySellerNewestWithStatusParams struct {
	SellerBotID string   `json:"seller_bot_id"`
	Statuses    []string `json:"statuses"`
	Limit       int64    `json:"limit"`
}

func (q *Queries) ListJobsBySellerNewestWithStatus(ctx context.Context, arg ListJobsBySellerNewestWithStatusParams) ([]Job, error) {
	query := listJobsBySellerNewestWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SellerBotID)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsBySellerSince = `-- name: ListJobsBySellerSince :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE seller_bot_id = ?1
	AND created_at >= ?2
ORDER BY created_at DESC, job_id DESC
LIMIT ?3
`

type ListJobsBySellerSinceParams struct {
	SellerBotID  string    `json:"seller_bot_id"`
	CreatedSince time.Time `json:"created_since"`
	Limit        int64     `json:"limit"`
}

func (q *Queries) ListJobsBySellerSince(ctx context.Context, arg ListJobsBySellerSinceParams) ([]Job, error) {
	rows, err := q.query(ctx, q.listJobsBySellerSinceStmt, listJobsBySellerSince, arg.SellerBotID, arg.CreatedSince, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsBySellerSinceAfter = `-- name: ListJobsBySellerSinceAfter :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE seller_bot_id = ?1
	AND created_at >= ?2
	AND (
		created_at < ?3
		OR (created_at = ?3 AND job_id < ?4)
	)
ORDER BY created_at DESC, job_id DESC
LIMIT ?5
`

type ListJobsBySellerSinceAfterParams struct {
	SellerBotID     string    `json:"seller_bot_id"`
	CreatedSince    time.Time `json:"created_since"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorJobID     string    `json:"cursor_job_id"`
	Limit           int64     `json:"limit"`
}

func (q *Queries) ListJobsBySellerSinceAfter(ctx context.Context, arg ListJobsBySellerSinceAfterParams) ([]Job, error) {
	rows, err := q.query(ctx, q.listJobsBySellerSinceAfterStmt, listJobsBySellerSinceAfter,
		arg.SellerBotID,
		arg.CreatedSince,
		arg.CursorCreatedAt,
		arg.CursorJobID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsBySellerSinceAfterWithStatus = `-- name: ListJobsBySellerSinceAfterWithStatus :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE seller_bot_id = ?1
	AND created_at >= ?2
	AND status IN (/*SLICE:statuses*/?)
	AND (
		created_at < ?4
		OR (created_at = ?4 AND job_id < ?5)
	)
ORDER BY created_at DESC, job_id DESC
LIMIT ?6
`

type ListJobsBySellerSinceAfterWithStatusParams struct {
	SellerBotID     string    `json:"seller_bot_id"`
	CreatedSince    time.Time `json:"created_since"`
	Statuses        []string  `json:"statuses"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorJobID     string    `json:"cursor_job_id"`
	Limit           int64     `json:"limit"`
}

func (q *Queries) ListJobsBySellerSinceAfterWithStatus(ctx context.Context, arg ListJobsBySellerSinceAfterWithStatusParams) ([]Job, error) {
	query := listJobsBySellerSinceAfterWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SellerBotID)
	queryParams = append(queryParams, arg.CreatedSince)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorJobID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsBySellerSinceWithStatus = `-- name: ListJobsBySellerSinceWithStatus :many
SELECT job_id, offer_id, buyer_bot_id, seller_bot_id, status, price_raw, turnaround_seconds, created_at, job_expires_at, request_payload_id, charge_id, charge_address, charge_amount_raw, charge_expires_at, charge_sig_ed25519, paid_at, delivered_at, cancelled_at, expired_at, payment_verifier, payment_block_hash, payment_observed_at, amount_raw_received FROM jobs
WHERE seller_bot_id = ?1
	AND created_at >= ?2
	AND status IN (/*SLICE:statuses*/?)
ORDER BY created_at DESC, job_id DESC
LIMIT ?4
`

type ListJobsBySellerSinceWithStatusParams struct {
	SellerBotID  string    `json:"seller_bot_id"`
	CreatedSince time.Time `json:"created_since"`
	Statuses     []string  `json:"statuses"`
	Limit        int64     `json:"limit"`
}

func (q *Queries) ListJobsBySellerSinceWithStatus(ctx context.Context, arg ListJobsBySellerSinceWithStatusParams) ([]Job, error) {
	query := listJobsBySellerSinceWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SellerBotID)
	queryParams = append(queryParams, arg.CreatedSince)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.JobID,
			&i.OfferID,
			&i.BuyerBotID,
			&i.SellerBotID,
			&i.Status,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.JobExpiresAt,
			&i.RequestPayloadID,
			&i.ChargeID,
			&i.ChargeAddress,
			&i.ChargeAmountRaw,
			&i.ChargeExpiresAt,
			&i.ChargeSigEd25519,
			&i.PaidAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.PaymentVerifier,
			&i.PaymentBlockHash,
			&i.PaymentObservedAt,
			&i.AmountRawReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferIDsByTag = `-- name: ListOfferIDsByTag :many
SELECT offer_id FROM offer_tags
WHERE tag = ?1
`

func (q *Queries) ListOfferIDsByTag(ctx context.Context, tag string) ([]string, error) {
	rows, err := q.query(ctx, q.listOfferIDsByTagStmt, listOfferIDsByTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var offer_id string
		if err := rows.Scan(&offer_id); err != nil {
			return nil, err
		}
		items = append(items, offer_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferTags = `-- name: ListOfferTags :many
SELECT tag FROM offer_tags
WHERE offer_id = ?1
ORDER BY tag ASC
`

func (q *Queries) ListOfferTags(ctx context.Context, offerID string) ([]string, error) {
	rows, err := q.query(ctx, q.listOfferTagsStmt, listOfferTags, offerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersNewest = `-- name: ListOffersNewest :many
SELECT offer_id, seller_bot_id, title, description, tags_json, price_raw, turnaround_seconds, created_at, expires_at, status, cancelled_at, request_schema_hint FROM offers
WHERE (?1 = '' OR seller_bot_id = ?1)
	AND (?2 = '' OR status = ?2)
	AND (?3 = '' OR title LIKE '%' || ?3 || '%' OR description LIKE '%' || ?3 || '%')
ORDER BY created_at DESC, offer_id DESC
LIMIT ?4
`

type ListOffersNewestParams struct {
	SellerBotID interface{} `json:"seller_bot_id"`
	Status      interface{} `json:"status"`
	Query       interface{} `json:"query"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) ListOffersNewest(ctx context.Context, arg ListOffersNewestParams) ([]Offer, error) {
	rows, err := q.query(ctx, q.listOffersNewestStmt, listOffersNewest,
		arg.SellerBotID,
		arg.Status,
		arg.Query,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.OfferID,
			&i.SellerBotID,
			&i.Title,
			&i.Description,
			&i.TagsJson,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.CancelledAt,
			&i.RequestSchemaHint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersNewestAfter = `-- name: ListOffersNewestAfter :many
SELECT offer_id, seller_bot_id, title, description, tags_json, price_raw, turnaround_seconds, created_at, expires_at, status, cancelled_at, request_schema_hint FROM offers
WHERE (?1 = '' OR seller_bot_id = ?1)
	AND (?2 = '' OR status = ?2)
	AND (?3 = '' OR title LIKE '%' || ?3 || '%' OR description LIKE '%' || ?3 || '%')
	AND (
		created_at < ?4
		OR (created_at = ?4 AND offer_id < ?5)
	)
ORDER BY created_at DESC, offer_id DESC
LIMIT ?6
`

type ListOffersNewestAfterParams struct {
	SellerBotID     interface{} `json:"seller_bot_id"`
	Status          interface{} `json:"status"`
	Query           interface{} `json:"query"`
	CursorCreatedAt time.Time   `json:"cursor_created_at"`
	CursorOfferID   string      `json:"cursor_offer_id"`
	Limit           int64       `json:"limit"`
}

func (q *Queries) ListOffersNewestAfter(ctx context.Context, arg ListOffersNewestAfterParams) ([]Offer, error) {
	rows, err := q.query(ctx, q.listOffersNewestAfterStmt, listOffersNewestAfter,
		arg.SellerBotID,
		arg.Status,
		arg.Query,
		arg.CursorCreatedAt,
		arg.CursorOfferID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.OfferID,
			&i.SellerBotID,
			&i.Title,
			&i.Description,
			&i.TagsJson,
			&i.PriceRaw,
			&i.TurnaroundSeconds,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.CancelledAt,
			&i.RequestSchemaHint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayloadMetadataAll = `-- name: ListPayloadMetadataAll :many
SELECT payload_id,
	job_id,
	sender_bot_id,
	recipient_bot_id,
	payload_kind,
	enc_alg,
	recipient_kid,
	created_at,
	fetched_at
FROM payloads
WHERE recipient_bot_id = ?1
	AND (?2 = '' OR job_id = ?2)
ORDER BY created_at DESC, payload_id DESC
LIMIT ?3
`

type ListPayloadMetadataAllParams struct {
	RecipientBotID string      `json:"recipient_bot_id"`
	JobID          interface{} `json:"job_id"`
	Limit          int64       `json:"limit"`
}

type ListPayloadMetadataAllRow struct {
	PayloadID      string       `json:"payload_id"`
	JobID          string       `json:"job_id"`
	SenderBotID    string       `json:"sender_bot_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
	PayloadKind    string       `json:"payload_kind"`
	EncAlg         string       `json:"enc_alg"`
	RecipientKid   string       `json:"recipient_kid"`
	CreatedAt      time.Time    `json:"created_at"`
	FetchedAt      sql.NullTime `json:"fetched_at"`
}

func (q *Queries) ListPayloadMetadataAll(ctx context.Context, arg ListPayloadMetadataAllParams) ([]ListPayloadMetadataAllRow, error) {
	rows, err := q.query(ctx, q.listPayloadMetadataAllStmt, listPayloadMetadataAll, arg.RecipientBotID, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayloadMetadataAllRow
	for rows.Next() {
		var i ListPayloadMetadataAllRow
		if err := rows.Scan(
			&i.PayloadID,
			&i.JobID,
			&i.SenderBotID,
			&i.RecipientBotID,
			&i.PayloadKind,
			&i.EncAlg,
			&i.RecipientKid,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayloadMetadataAllAfter = `-- name: ListPayloadMetadataAllAfter :many
SELECT payload_id,
	job_id,
	sender_bot_id,
	recipient_bot_id,
	payload_kind,
	enc_alg,
	recipient_kid,
	created_at,
	fetched_at
FROM payloads
WHERE recipient_bot_id = ?1
	AND (?2 = '' OR job_id = ?2)
	AND (
		created_at < ?3
		OR (created_at = ?3 AND payload_id < ?4)
	)
ORDER BY created_at DESC, payload_id DESC
LIMIT ?5
`

type ListPayloadMetadataAllAfterParams struct {
	RecipientBotID  string      `json:"recipient_bot_id"`
	JobID           interface{} `json:"job_id"`
	CursorCreatedAt time.Time   `json:"cursor_created_at"`
	CursorPayloadID string      `json:"cursor_payload_id"`
	Limit           int64       `json:"limit"`
}

type ListPayloadMetadataAllAfterRow struct {
	PayloadID      string       `json:"payload_id"`
	JobID          string       `json:"job_id"`
	SenderBotID    string       `json:"sender_bot_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
	PayloadKind    string       `json:"payload_kind"`
	EncAlg         string       `json:"enc_alg"`
	RecipientKid   string       `json:"recipient_kid"`
	CreatedAt      time.Time    `json:"created_at"`
	FetchedAt      sql.NullTime `json:"fetched_at"`
}

func (q *Queries) ListPayloadMetadataAllAfter(ctx context.Context, arg ListPayloadMetadataAllAfterParams) ([]ListPayloadMetadataAllAfterRow, error) {
	rows, err := q.query(ctx, q.listPayloadMetadataAllAfterStmt, listPayloadMetadataAllAfter,
		arg.RecipientBotID,
		arg.JobID,
		arg.CursorCreatedAt,
		arg.CursorPayloadID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayloadMetadataAllAfterRow
	for rows.Next() {
		var i ListPayloadMetadataAllAfterRow
		if err := rows.Scan(
			&i.PayloadID,
			&i.JobID,
			&i.SenderBotID,
			&i.RecipientBotID,
			&i.PayloadKind,
			&i.EncAlg,
			&i.RecipientKid,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayloadMetadataFetched = `-- name: ListPayloadMetadataFetched :many
SELECT payload_id,
	job_id,
	sender_bot_id,
	recipient_bot_id,
	payload_kind,
	enc_alg,
	recipient_kid,
	created_at,
	fetched_at
FROM payloads
WHERE recipient_bot_id = ?1
	AND (?2 = '' OR job_id = ?2)
	AND fetched_at IS NOT NULL
ORDER BY created_at DESC, payload_id DESC
LIMIT ?3
`

type ListPayloadMetadataFetchedParams struct {
	RecipientBotID string      `json:"recipient_bot_id"`
	JobID          interface{} `json:"job_id"`
	Limit          int64       `json:"limit"`
}

type ListPayloadMetadataFetchedRow struct {
	PayloadID      string       `json:"payload_id"`
	JobID          string       `json:"job_id"`
	SenderBotID    string       `json:"sender_bot_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
	PayloadKind    string       `json:"payload_kind"`
	EncAlg         string       `json:"enc_alg"`
	RecipientKid   string       `json:"recipient_kid"`
	CreatedAt      time.Time    `json:"created_at"`
	FetchedAt      sql.NullTime `json:"fetched_at"`
}

func (q *Queries) ListPayloadMetadataFetched(ctx context.Context, arg ListPayloadMetadataFetchedParams) ([]ListPayloadMetadataFetchedRow, error) {
	rows, err := q.query(ctx, q.listPayloadMetadataFetchedStmt, listPayloadMetadataFetched, arg.RecipientBotID, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayloadMetadataFetchedRow
	for rows.Next() {
		var i ListPayloadMetadataFetchedRow
		if err := rows.Scan(
			&i.PayloadID,
			&i.JobID,
			&i.SenderBotID,
			&i.RecipientBotID,
			&i.PayloadKind,
			&i.EncAlg,
			&i.RecipientKid,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayloadMetadataFetchedAfter = `-- name: ListPayloadMetadataFetchedAfter :many
SELECT payload_id,
	job_id,
	sender_bot_id,
	recipient_bot_id,
	payload_kind,
	enc_alg,
	recipient_kid,
	created_at,
	fetched_at
FROM payloads
WHERE recipient_bot_id = ?1
	AND (?2 = '' OR job_id = ?2)
	AND fetched_at IS NOT NULL
	AND (
		created_at < ?3
		OR (created_at = ?3 AND payload_id < ?4)
	)
ORDER BY created_at DESC, payload_id DESC
LIMIT ?5
`

type ListPayloadMetadataFetchedAfterParams struct {
	RecipientBotID  string      `json:"recipient_bot_id"`
	JobID           interface{} `json:"job_id"`
	CursorCreatedAt time.Time   `json:"cursor_created_at"`
	CursorPayloadID string      `json:"cursor_payload_id"`
	Limit           int64       `json:"limit"`
}

type ListPayloadMetadataFetchedAfterRow struct {
	PayloadID      string       `json:"payload_id"`
	JobID          string       `json:"job_id"`
	SenderBotID    string       `json:"sender_bot_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
	PayloadKind    string       `json:"payload_kind"`
	EncAlg         string       `json:"enc_alg"`
	RecipientKid   string       `json:"recipient_kid"`
	CreatedAt      time.Time    `json:"created_at"`
	FetchedAt      sql.NullTime `json:"fetched_at"`
}

func (q *Queries) ListPayloadMetadataFetchedAfter(ctx context.Context, arg ListPayloadMetadataFetchedAfterParams) ([]ListPayloadMetadataFetchedAfterRow, error) {
	rows, err := q.query(ctx, q.listPayloadMetadataFetchedAfterStmt, listPayloadMetadataFetchedAfter,
		arg.RecipientBotID,
		arg.JobID,
		arg.CursorCreatedAt,
		arg.CursorPayloadID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayloadMetadataFetchedAfterRow
	for rows.Next() {
		var i ListPayloadMetadataFetchedAfterRow
		if err := rows.Scan(
			&i.PayloadID,
			&i.JobID,
			&i.SenderBotID,
			&i.RecipientBotID,
			&i.PayloadKind,
			&i.EncAlg,
			&i.RecipientKid,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayloadMetadataUnfetched = `-- name: ListPayloadMetadataUnfetched :many
SELECT payload_id,
	job_id,
	sender_bot_id,
	recipient_bot_id,
	payload_kind,
	enc_alg,
	recipient_kid,
	created_at,
	fetched_at
FROM payloads
WHERE recipient_bot_id = ?1
	AND (?2 = '' OR job_id = ?2)
	AND fetched_at IS NULL
ORDER BY created_at DESC, payload_id DESC
LIMIT ?3
`

type ListPayloadMetadataUnfetchedParams struct {
	RecipientBotID string      `json:"recipient_bot_id"`
	JobID          interface{} `json:"job_id"`
	Limit          int64       `json:"limit"`
}

type ListPayloadMetadataUnfetchedRow struct {
	PayloadID      string       `json:"payload_id"`
	JobID          string       `json:"job_id"`
	SenderBotID    string       `json:"sender_bot_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
	PayloadKind    string       `json:"payload_kind"`
	EncAlg         string       `json:"enc_alg"`
	RecipientKid   string       `json:"recipient_kid"`
	CreatedAt      time.Time    `json:"created_at"`
	FetchedAt      sql.NullTime `json:"fetched_at"`
}

func (q *Queries) ListPayloadMetadataUnfetched(ctx context.Context, arg ListPayloadMetadataUnfetchedParams) ([]ListPayloadMetadataUnfetchedRow, error) {
	rows, err := q.query(ctx, q.listPayloadMetadataUnfetchedStmt, listPayloadMetadataUnfetched, arg.RecipientBotID, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayloadMetadataUnfetchedRow
	for rows.Next() {
		var i ListPayloadMetadataUnfetchedRow
		if err := rows.Scan(
			&i.PayloadID,
			&i.JobID,
			&i.SenderBotID,
			&i.RecipientBotID,
			&i.PayloadKind,
			&i.EncAlg,
			&i.RecipientKid,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayloadMetadataUnfetchedAfter = `-- name: ListPayloadMetadataUnfetchedAfter :many
SELECT payload_id,
	job_id,
	sender_bot_id,
	recipient_bot_id,
	payload_kind,
	enc_alg,
	recipient_kid,
	created_at,
	fetched_at
FROM payloads
WHERE recipient_bot_id = ?1
	AND (?2 = '' OR job_id = ?2)
	AND fetched_at IS NULL
	AND (
		created_at < ?3
		OR (created_at = ?3 AND payload_id < ?4)
	)
ORDER BY created_at DESC, payload_id DESC
LIMIT ?5
`

type ListPayloadMetadataUnfetchedAfterParams struct {
	RecipientBotID  string      `json:"recipient_bot_id"`
	JobID           interface{} `json:"job_id"`
	CursorCreatedAt time.Time   `json:"cursor_created_at"`
	CursorPayloadID string      `json:"cursor_payload_id"`
	Limit           int64       `json:"limit"`
}

type ListPayloadMetadataUnfetchedAfterRow struct {
	PayloadID      string       `json:"payload_id"`
	JobID          string       `json:"job_id"`
	SenderBotID    string       `json:"sender_bot_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
	PayloadKind    string       `json:"payload_kind"`
	EncAlg         string       `json:"enc_alg"`
	RecipientKid   string       `json:"recipient_kid"`
	CreatedAt      time.Time    `json:"created_at"`
	FetchedAt      sql.NullTime `json:"fetched_at"`
}

func (q *Queries) ListPayloadMetadataUnfetchedAfter(ctx context.Context, arg ListPayloadMetadataUnfetchedAfterParams) ([]ListPayloadMetadataUnfetchedAfterRow, error) {
	rows, err := q.query(ctx, q.listPayloadMetadataUnfetchedAfterStmt, listPayloadMetadataUnfetchedAfter,
		arg.RecipientBotID,
		arg.JobID,
		arg.CursorCreatedAt,
		arg.CursorPayloadID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayloadMetadataUnfetchedAfterRow
	for rows.Next() {
		var i ListPayloadMetadataUnfetchedAfterRow
		if err := rows.Scan(
			&i.PayloadID,
			&i.JobID,
			&i.SenderBotID,
			&i.RecipientBotID,
			&i.PayloadKind,
			&i.EncAlg,
			&i.RecipientKid,
			&i.CreatedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamEventsAfterCursor = `-- name: ListStreamEventsAfterCursor :many
SELECT stream_key,
	cursor,
	event_type,
	payload_json,
	created_at
FROM stream_events
WHERE stream_key = ?1
	AND cursor > ?2
ORDER BY cursor ASC
LIMIT ?3
`

type ListStreamEventsAfterCursorParams struct {
	StreamKey   string `json:"stream_key"`
	SinceCursor int64  `json:"since_cursor"`
	Limit       int64  `json:"limit"`
}

type ListStreamEventsAfterCursorRow struct {
	StreamKey   string    `json:"stream_key"`
	Cursor      int64     `json:"cursor"`
	EventType   string    `json:"event_type"`
	PayloadJson string    `json:"payload_json"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListStreamEventsAfterCursor(ctx context.Context, arg ListStreamEventsAfterCursorParams) ([]ListStreamEventsAfterCursorRow, error) {
	rows, err := q.query(ctx, q.listStreamEventsAfterCursorStmt, listStreamEventsAfterCursor, arg.StreamKey, arg.SinceCursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamEventsAfterCursorRow
	for rows.Next() {
		var i ListStreamEventsAfterCursorRow
		if err := rows.Scan(
			&i.StreamKey,
			&i.Cursor,
			&i.EventType,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPayloadFetched = `-- name: MarkPayloadFetched :exec
UPDATE payloads
SET fetched_at = ?1
WHERE payload_id = ?2
	AND recipient_bot_id = ?3
`

type MarkPayloadFetchedParams struct {
	FetchedAt      sql.NullTime `json:"fetched_at"`
	PayloadID      string       `json:"payload_id"`
	RecipientBotID string       `json:"recipient_bot_id"`
}

func (q *Queries) MarkPayloadFetched(ctx context.Context, arg MarkPayloadFetchedParams) error {
	_, err := q.exec(ctx, q.markPayloadFetchedStmt, markPayloadFetched, arg.FetchedAt, arg.PayloadID, arg.RecipientBotID)
	return err
}

const updateBotLastSeen = `-- name: UpdateBotLastSeen :exec
UPDATE bots
SET last_seen_at = ?1
WHERE bot_id = ?2
`

type UpdateBotLastSeenParams struct {
	LastSeenAt sql.NullTime `json:"last_seen_at"`
	BotID      string       `json:"bot_id"`
}

func (q *Queries) UpdateBotLastSeen(ctx context.Context, arg UpdateBotLastSeenParams) error {
	_, err := q.exec(ctx, q.updateBotLastSeenStmt, updateBotLastSeen, arg.LastSeenAt, arg.BotID)
	return err
}

const updateBotRevoke = `-- name: UpdateBotRevoke :one
UPDATE bots
SET revoked_at = COALESCE(revoked_at, ?1)
WHERE bot_id = ?2
RETURNING bot_id, signing_pubkey_ed25519, encryption_pubkey_x25519, signing_kid, encryption_kid, created_at, last_seen_at, revoked_at
`

type UpdateBotRevokeParams struct {
	RevokedAt sql.NullTime `json:"revoked_at"`
	BotID     string       `json:"bot_id"`
}

func (q *Queries) UpdateBotRevoke(ctx context.Context, arg UpdateBotRevokeParams) (Bot, error) {
	row := q.queryRow(ctx, q.updateBotRevokeStmt, updateBotRevoke, arg.RevokedAt, arg.BotID)
	var i Bot
	err := row.Scan(
		&i.BotID,
		&i.SigningPubkeyEd25519,
		&i.EncryptionPubkeyX25519,
		&i.SigningKid,
		&i.EncryptionKid,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateJobCancel = `-- name: UpdateJobCancel :exec
UPDATE jobs
SET status = 'CANCELLED',
	cancelled_at = ?1
WHERE job_id = ?2
	AND status = 'REQUESTED'
`

type UpdateJobCancelParams struct {
	CancelledAt sql.NullTime `json:"cancelled_at"`
	JobID       string       `json:"job_id"`
}

func (q *Queries) UpdateJobCancel(ctx context.Context, arg UpdateJobCancelParams) error {
	_, err := q.exec(ctx, q.updateJobCancelStmt, updateJobCancel, arg.CancelledAt, arg.JobID)
	return err
}

const updateJobCharge = `-- name: UpdateJobCharge :exec
UPDATE jobs
SET status = 'CHARGE_CREATED',
	charge_id = ?1,
	charge_address = ?2,
	charge_amount_raw = ?3,
	charge_expires_at = ?4,
	charge_sig_ed25519 = ?5
WHERE job_id = ?6
	AND status = 'REQUESTED'
	AND charge_id IS NULL
`

type UpdateJobChargeParams struct {
	ChargeID         sql.NullString `json:"charge_id"`
	ChargeAddress    sql.NullString `json:"charge_address"`
	ChargeAmountRaw  sql.NullString `json:"charge_amount_raw"`
	ChargeExpiresAt  sql.NullTime   `json:"charge_expires_at"`
	ChargeSigEd25519 sql.NullString `json:"charge_sig_ed25519"`
	JobID            string         `json:"job_id"`
}

func (q *Queries) UpdateJobCharge(ctx context.Context, arg UpdateJobChargeParams) error {
	_, err := q.exec(ctx, q.updateJobChargeStmt, updateJobCharge,
		arg.ChargeID,
		arg.ChargeAddress,
		arg.ChargeAmountRaw,
		arg.ChargeExpiresAt,
		arg.ChargeSigEd25519,
		arg.JobID,
	)
	return err
}

const updateJobDeliver = `-- name: UpdateJobDeliver :exec
UPDATE jobs
SET status = 'DELIVERED',
	delivered_at = ?1
WHERE job_id = ?2
	AND status = 'PAID'
`

type UpdateJobDeliverParams struct {
	DeliveredAt sql.NullTime `json:"delivered_at"`
	JobID       string       `json:"job_id"`
}

func (q *Queries) UpdateJobDeliver(ctx context.Context, arg UpdateJobDeliverParams) error {
	_, err := q.exec(ctx, q.updateJobDeliverStmt, updateJobDeliver, arg.DeliveredAt, arg.JobID)
	return err
}

const updateJobExpire = `-- name: UpdateJobExpire :exec
UPDATE jobs
SET status = 'EXPIRED',
	expired_at = ?1
WHERE job_id = ?2
	AND status IN ('REQUESTED', 'CHARGE_CREATED', 'PAID')
`

type UpdateJobExpireParams struct {
	ExpiredAt sql.NullTime `json:"expired_at"`
	JobID     string       `json:"job_id"`
}

func (q *Queries) UpdateJobExpire(ctx context.Context, arg UpdateJobExpireParams) error {
	_, err := q.exec(ctx, q.updateJobExpireStmt, updateJobExpire, arg.ExpiredAt, arg.JobID)
	return err
}

const updateJobMarkPaid = `-- name: UpdateJobMarkPaid :exec
UPDATE jobs
SET status = 'PAID',
	paid_at = ?1,
	payment_verifier = ?2,
	payment_block_hash = ?3,
	payment_observed_at = ?4,
	amount_raw_received = ?5
WHERE job_id = ?6
	AND status = 'CHARGE_CREATED'
`

type UpdateJobMarkPaidParams struct {
	PaidAt            sql.NullTime   `json:"paid_at"`
	PaymentVerifier   sql.NullString `json:"payment_verifier"`
	PaymentBlockHash  sql.NullString `json:"payment_block_hash"`
	PaymentObservedAt sql.NullTime   `json:"payment_observed_at"`
	AmountRawReceived sql.NullString `json:"amount_raw_received"`
	JobID             string         `json:"job_id"`
}

func (q *Queries) UpdateJobMarkPaid(ctx context.Context, arg UpdateJobMarkPaidParams) error {
	_, err := q.exec(ctx, q.updateJobMarkPaidStmt, updateJobMarkPaid,
		arg.PaidAt,
		arg.PaymentVerifier,
		arg.PaymentBlockHash,
		arg.PaymentObservedAt,
		arg.AmountRawReceived,
		arg.JobID,
	)
	return err
}

const updateOfferCancel = `-- name: UpdateOfferCancel :exec
UPDATE offers
SET status = 'CANCELLED',
	cancelled_at = ?1
WHERE offer_id = ?2
	AND status IN ('ACTIVE', 'PAUSED')
`

type UpdateOfferCancelParams struct {
	CancelledAt sql.NullTime `json:"cancelled_at"`
	OfferID     string       `json:"offer_id"`
}

func (q *Queries) UpdateOfferCancel(ctx context.Context, arg UpdateOfferCancelParams) error {
	_, err := q.exec(ctx, q.updateOfferCancelStmt, updateOfferCancel, arg.CancelledAt, arg.OfferID)
	return err
}

const updateOfferExpire = `-- name: UpdateOfferExpire :exec
UPDATE offers
SET status = 'EXPIRED'
WHERE offer_id = ?1
	AND status IN ('ACTIVE', 'PAUSED')
`

func (q *Queries) UpdateOfferExpire(ctx context.Context, offerID string) error {
	_, err := q.exec(ctx, q.updateOfferExpireStmt, updateOfferExpire, offerID)
	return err
}

const updateOfferPause = `-- name: UpdateOfferPause :exec
UPDATE offers
SET status = 'PAUSED'
WHERE offer_id = ?1
	AND status = 'ACTIVE'
`

func (q *Queries) UpdateOfferPause(ctx context.Context, offerID string) error {
	_, err := q.exec(ctx, q.updateOfferPauseStmt, updateOfferPause, offerID)
	return err
}

const updateOfferResume = `-- name: UpdateOfferResume :exec
UPDATE offers
SET status = 'ACTIVE'
WHERE offer_id = ?1
	AND status = 'PAUSED'
`

func (q *Queries) UpdateOfferResume(ctx context.Context, offerID string) error {
	_, err := q.exec(ctx, q.updateOfferResumeStmt, updateOfferResume, offerID)
	return err
}

const upsertPollAck = `-- name: UpsertPollAck :exec
INSERT INTO poll_acks (
	recipient_bot_id,
	last_acked_event_id,
	updated_at
) VALUES (
	?1,
	?2,
	?3
)
ON CONFLICT(recipient_bot_id) DO UPDATE SET
	last_acked_event_id = excluded.last_acked_event_id,
	updated_at = excluded.updated_at
`

type UpsertPollAckParams struct {
	RecipientBotID   string    `json:"recipient_bot_id"`
	LastAckedEventID int64     `json:"last_acked_event_id"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) UpsertPollAck(ctx context.Context, arg UpsertPollAckParams) error {
	_, err := q.exec(ctx, q.upsertPollAckStmt, upsertPollAck, arg.RecipientBotID, arg.LastAckedEventID, arg.UpdatedAt)
	return err
}

const upsertStreamAck = `-- name: UpsertStreamAck :exec
INSERT INTO stream_acks (
	stream_key,
	ack_cursor,
	updated_at
) VALUES (
	?1,
	?2,
	?3
)
ON CONFLICT(stream_key) DO UPDATE SET
	ack_cursor = excluded.ack_cursor,
	updated_at = excluded.updated_at
`

type UpsertStreamAckParams struct {
	StreamKey string    `json:"stream_key"`
	AckCursor int64     `json:"ack_cursor"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpsertStreamAck(ctx context.Context, arg UpsertStreamAckParams) error {
	_, err := q.exec(ctx, q.upsertStreamAckStmt, upsertStreamAck, arg.StreamKey, arg.AckCursor, arg.UpdatedAt)
	return err
}
